### ISSUE TITLE
can't find "afxres.h" in resource.rc

### ISSUE THREAD

**Issue by iowrite** [tomwillow/2048#2]
just like the title described
![image](https://user-images.githubusercontent.com/49424837/61350741-27a47f80-a89b-11e9-8b0b-ba77a5803546.png)

**Comment by tomwillow** [comment]
This error is due to that you didn't use the given ".sln" file. My ".sln" file contains the setting of compiling to aviod to us the "afxres.h" file, which is created as the default file when VS create a new project.
Or you can set your VS project by finding the setting of "Not use pre-compile head file "afxres.h"".

**Comment by llzgc** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，邮件已收到，我会尽快和您联系。祝生活愉快：)
